services:
  db:
    image: mysql:8
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: 19981998M.gh
      MYSQL_DATABASE: cards
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./database
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 19981998M.gh
      DB_NAME: cards
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
